const LABELS = {
  links: 'Links do menu',
  label: 'Texto',
  href: 'Link (URL)',
  cta: 'Texto do botão',
  headline: 'Título principal',
  line1: 'Linha 1',
  line2: 'Linha 2',
  emphasis1: 'Palavra em destaque 1',
  emphasis2: 'Palavra em destaque 2',
  middle: 'Texto do meio',
  end: 'Texto final',
  before: 'Texto antes do destaque',
  emphasis: 'Palavra em destaque',
  paragraph: 'Parágrafo',
  paragraph1: 'Parágrafo 1',
  paragraph2: 'Parágrafo 2',
  text: 'Texto',
  partnersLabel: 'Texto acima dos logos de parceiros',
  articles: 'Artigos/publicações',
  badge: 'Selo',
  source: 'Fonte',
  title: 'Título',
  heading: 'Título',
  subheading: 'Subtítulo',
  description: 'Descrição',
  boxes: 'Caixas de benefício',
  items: 'Itens',
  tagline: 'Frase de efeito',
  groups: 'Nomes dos grupos',
  researchers: 'Nome do grupo: pesquisadores',
  medical: 'Nome do grupo: conselho médico',
  button: 'Botão',
  hero: 'Topo da página',
  subtitle: 'Subtítulo',
  ctaJobs: 'Botão: ver vagas',
  ctaHow: 'Botão: como trabalhamos',
  company: 'Sobre a empresa',
  titleStart: 'Início do título',
  p1: 'Parágrafo 1',
  p2: 'Parágrafo 2',
  statsLabel: 'Label das estatísticas',
  stats: 'Estatísticas',
  k: 'Rótulo curto',
  num: 'Número',
  desc: 'Descrição',
  locationLabel: 'Rótulo de localização',
  locationCity: 'Cidade',
  locationAddress: 'Endereço completo',
  beliefs: 'Crenças/valores',
  faq: 'Perguntas frequentes',
  q: 'Pergunta',
  a: 'Resposta',
  jobs: 'Vagas',
  modality: 'Modalidade de trabalho',
  internTag: 'Etiqueta: estágio',
  juniorTag: 'Etiqueta: júnior',
  applyLabel: 'Texto do botão de candidatura',
  comingSoon: 'Texto para "em breve"',
  list: 'Lista de vagas',
  level: 'Nível',
  talent: 'Banco de talentos',
  tagline2: 'Frase de efeito',
  socials: 'Redes sociais',
  sections: 'Nomes das seções',
  products: 'Produtos',
  address: 'Endereço',
  partners: 'Parceiros',
  productLinks: 'Links de produtos',
  legalLinks: 'Links legais',
  copyright: 'Texto de direitos autorais',
  name: 'Nome',
  degree: 'Formação',
  role: 'Cargo',
  group: 'Grupo',
  img: 'URL da imagem',
  bio: 'Biografia',
  benefits: 'Benefícios',
  icon: 'URL do ícone',
  bg: 'Cor de fundo',
  bullets: 'Marcadores',
  category: 'Categoria',
  h: 'Altura (px)',
  src: 'URL da imagem',
  blend: 'Modo de mistura (blend)',
  filter: 'Filtro CSS',
}

export function labelFor(key: string): string {
  if (key in LABELS) return LABELS[key as keyof typeof LABELS]
  const spaced = key
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/_/g, ' ')
    .toLowerCase()
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}
